# Generated by Django 3.1.3 on 2021-01-13 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Czytelnik',
            fields=[
                ('idCzytelnik', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
                ('wiek', models.IntegerField()),
                ('adres', models.CharField(max_length=150)),
                ('telefon', models.CharField(max_length=11)),
                ('owner', models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='dodani_czytelnicy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nazwisko',),
            },
        ),
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoria', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'ordering': ('kategoria',),
            },
        ),
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('idKsiazka', models.AutoField(primary_key=True, serialize=False)),
                ('tytul', models.CharField(max_length=300)),
                ('autor', models.CharField(max_length=50)),
                ('minimalny_wiek_czytelnika', models.IntegerField()),
                ('data_wydania', models.DateField()),
                ('gatunek', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ksiazki', to='Biblioteka.gatunek')),
                ('owner', models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='dodane_ksiazki', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('tytul',),
            },
        ),
        migrations.CreateModel(
            name='HistoriaWypozyczen',
            fields=[
                ('idZwrot', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('data_wypozyczenia', models.DateField()),
                ('data_zwrotu', models.DateField()),
                ('czytelnik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historia', to='Biblioteka.czytelnik')),
                ('ksiazka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Biblioteka.ksiazka')),
            ],
            options={
                'ordering': ('czytelnik',),
            },
        ),
        migrations.CreateModel(
            name='AktualneWypozyczenia',
            fields=[
                ('idWypozyczenia', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('data_wypozyczenia', models.DateField(auto_now=True)),
                ('czytelnik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aktualnieWypozyczoneKsiazki', to='Biblioteka.czytelnik')),
                ('ksiazka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Biblioteka.ksiazka')),
            ],
            options={
                'ordering': ('czytelnik',),
            },
        ),
    ]
