# Generated by Django 3.1.3 on 2021-01-14 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktualnewypozyczenia',
            name='czytelnik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aktualnieWypozyczoneKsiazki', to='Biblioteka.czytelnik'),
        ),
        migrations.AlterField(
            model_name='historiawypozyczen',
            name='czytelnik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='historia', to='Biblioteka.czytelnik'),
        ),
    ]
