# Generated by Django 3.1.3 on 2021-01-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0002_auto_20210114_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksiazka',
            name='czy_wypozyczona',
            field=models.BooleanField(default=False),
        ),
    ]
