# Generated by Django 3.1.3 on 2021-01-16 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Biblioteka', '0004_auto_20210116_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czytelnik',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dodani_czytelnicy', to=settings.AUTH_USER_MODEL),
        ),
    ]
