# Generated by Django 3.1.3 on 2021-01-16 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Biblioteka', '0005_auto_20210116_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dodane_ksiazki', to=settings.AUTH_USER_MODEL),
        ),
    ]
