# Generated by Django 3.1.3 on 2021-01-17 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0006_auto_20210116_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aktualnewypozyczenia',
            options={'ordering': ('idWypozyczenia',)},
        ),
        migrations.AlterModelOptions(
            name='czytelnik',
            options={'ordering': ('idCzytelnik',)},
        ),
        migrations.AlterModelOptions(
            name='historiawypozyczen',
            options={'ordering': ('idZwrot',)},
        ),
        migrations.AlterModelOptions(
            name='ksiazka',
            options={'ordering': ('idKsiazka',)},
        ),
    ]
