# Generated by Django 3.1.3 on 2021-01-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0007_auto_20210117_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='czytelnik',
            name='kod_dostepu',
            field=models.IntegerField(default=0),
        ),
    ]
