# Generated by Django 3.1.3 on 2020-12-01 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Czytelnik',
            fields=[
                ('idCzytelnik', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
                ('wiek', models.IntegerField()),
                ('adres', models.CharField(max_length=150)),
                ('telefon', models.CharField(max_length=11)),
                ('login', models.CharField(max_length=30, unique=True)),
                ('haslo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('idKsiazka', models.AutoField(primary_key=True, serialize=False)),
                ('tytul', models.CharField(max_length=300)),
                ('autor', models.CharField(max_length=50)),
                ('minimalny_wiek_czytelnika', models.IntegerField()),
                ('data_wydania', models.DateField()),
                ('gatunek', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('idPracownik', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
                ('wiek', models.IntegerField()),
                ('adres', models.CharField(max_length=30)),
                ('telefon', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=30, unique=True)),
                ('haslo', models.CharField(max_length=30)),
                ('stanowisko', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WypozyczoneKsiazki',
            fields=[
                ('idWypozyczenie', models.AutoField(primary_key=True, serialize=False)),
                ('data_wypozyczenia', models.DateField(auto_now=True)),
                ('idCzytelnika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteka.czytelnik')),
                ('idKsiazki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteka.ksiazka')),
            ],
        ),
        migrations.CreateModel(
            name='PunktOdbiorczy',
            fields=[
                ('numer_schowka', models.IntegerField(primary_key=True, serialize=False)),
                ('haslo', models.CharField(max_length=5)),
                ('przechowywane_ksiazki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteka.ksiazka')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaWypozyczen',
            fields=[
                ('idZwrot', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('data_wypozyczenia', models.DateField(auto_now=True)),
                ('data_zwrotu', models.DateField()),
                ('idCzytelnika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteka.czytelnik')),
                ('idKsiazki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteka.ksiazka')),
            ],
        ),
    ]
